name: Deploy Node App via SSM
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
 
      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command --document-name "AWS-RunShellScript" \
          --targets "Key=tag:App,Values=Assignment" \
          --comment "Deploy Node App" \
          --parameters 'commands=[
            "set -e",
            "echo START DEPLOY",
            "sudo yum install -y nodejs npm git",
            "sudo npm install -g pm2",
            "pm2 -v",
            "sudo mkdir -p /var/www/app",
            "cd /var/www/app",
            "if [ ! -d .git ]; then sudo git clone https://github.com/SwagataMondal19/Assignment-App.git .; else sudo git pull origin main; fi",
            "npm install",
            "pm2 stop app || true",
            "pm2 start app.js --name app",
            "pm2 save",
            "curl -f http://localhost:3000/health",
            "echo DEPLOY COMPLETE"
          ]' \
          --region ap-south-1
